# Generated by Django 5.2.8 on 2026-01-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_teams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("administratrice", "Administratrice"),
                    ("cheffe", "Cheffe"),
                    ("user", "User"),
                ],
                default="user",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
