# Generated by Django 5.2.8 on 2025-12-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CampaignTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "template_type",
                    models.CharField(
                        choices=[("simple", "Simple"), ("typed", "Typed")],
                        max_length=10,
                    ),
                ),
                ("restriction_enzyme", models.CharField(max_length=50)),
                ("separator", models.CharField(default=".", max_length=5)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
