# Generated by Django 5.2.8 on 2026-01-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigntemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
