# Generated by Django 5.2.8 on 2026-02-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_campaigntemplate_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigntemplate",
            name="source_file",
            field=models.FileField(blank=True, null=True, upload_to="templates/"),
        ),
    ]
