<<<<<<< HEAD
# Generated by Django 5.2.8 on 2026-01-20 19:56
=======
# Generated by Django 5.0.14 on 2026-02-03 14:21
>>>>>>> muyao_publish_plasmide

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_object_id", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_CHEFFE", "Pending (Cheffe)"),
                            ("REJECTED_BY_CHEFFE", "Rejected by cheffe"),
                            ("PENDING_ADMIN", "Pending (Admin)"),
                            ("REJECTED_BY_ADMIN", "Rejected by admin"),
                            ("APPROVED", "Approved"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("cheffe_review_comment", models.TextField(blank=True)),
                ("cheffe_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_review_comment", models.TextField(blank=True)),
                ("admin_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_reviewed_publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cheffe_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cheffe_reviewed_publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
<<<<<<< HEAD
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.team",
                    ),
                ),
                (
=======
>>>>>>> muyao_publish_plasmide
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication request",
                "verbose_name_plural": "Publication requests",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status"], name="publication_status_40d0d3_idx"
                    ),
                    models.Index(
                        fields=["target_content_type", "target_object_id"],
                        name="publication_target__00cb7e_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING_CHEFFE", "PENDING_ADMIN"])),
                fields=("target_content_type", "target_object_id"),
                name="unique_pending_publication_request",
            ),
        ),
    ]
