# Generated by Django 5.0.14 on 2026-01-25 14:43

import django.db.models.deletion
import django.utils.timezone
# Generated by Django 5.2.8 on 2026-01-20 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("teams", "0005_alter_team_members_delete_teammembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            name="PublicationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_object_id", models.PositiveIntegerField()),
                ("object_id", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewed_comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                            ("PENDING_TEAM_LEAD", "Pending team lead"),
                            ("PENDING_ADMIN", "Pending admin"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING_ADMIN",
                        max_length=32,
                    ),
                ),
                ("team_validated_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_publications",
                        related_name="publication_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="teams.team",
                    ),
                ),
                (
                    "team_validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publication_team_validations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication request",
                "verbose_name_plural": "Publication requests",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status"], name="publication_status_40d0d3_idx"
                    ),
                    models.Index(
                        fields=["target_content_type", "target_object_id"],
                        name="publication_target__00cb7e_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("target_content_type", "target_object_id"),
                name="unique_pending_publication_request",
            ),
        ),
                "indexes": [
                    models.Index(
                        fields=["status"], name="publication_status_3e7c21_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="publication_content_570e88_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id"),
                        name="uniq_publication_request_per_target",
                    )
                ],
            },
        ),
    ]
