# Generated by Django 5.0.14 on 2026-02-05 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publication_requests",
                to="accounts.team",
            ),
        ),
    ]
