# Generated by Django 5.2.8 on 2026-01-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondences", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correspondenceentry",
            name="entry_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
