# Generated by Django 5.0.14 on 2026-01-06 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondences", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrespondenceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=200)),
                ("entry_type", models.CharField(max_length=100)),
                (
                    "correspondence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="correspondences.correspondence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Correspondence Entry",
                "verbose_name_plural": "Correspondence Entries",
                "ordering": ("correspondence_id", "identifier"),
            },
        ),
        migrations.AddConstraint(
            model_name="correspondenceentry",
            constraint=models.UniqueConstraint(
                fields=("correspondence", "identifier"),
                name="unique_correspondence_identifier",
            ),
        ),
    ]
