# Generated by Django 5.0.14 on 2026-02-03 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondences", "0002_alter_correspondenceentry_entry_type"),
        ("teams", "0005_alter_team_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correspondences",
                to="teams.team",
            ),
        ),
    ]
