# Generated by Django 5.0.14 on 2026-01-03 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plasmid",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("identifier", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=50)),
                ("sequence", models.TextField()),
                ("is_public", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Plasmid",
                "verbose_name_plural": "Plasmids",
                "ordering": ("id", "identifier"),
            },
        ),
        migrations.CreateModel(
            name="PlasmidCollection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plasmid_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plasmid_collections",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plasmid Collection",
                "verbose_name_plural": "Plasmid Collections",
                "ordering": ("id", "name"),
            },
        ),
    ]
