# Generated by Django 5.2.8 on 2026-02-02 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plasmid",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("identifier", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=50)),
                ("sequence", models.TextField()),
                ("length", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("genbank_data", models.JSONField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Plasmid",
                "verbose_name_plural": "Plasmids",
                "ordering": ("id", "identifier"),
            },
        ),
        migrations.CreateModel(
            name="PlasmidAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_type", models.CharField(max_length=50)),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("strand", models.IntegerField()),
                ("label", models.CharField(blank=True, max_length=200)),
                ("qualifiers", models.JSONField(blank=True, null=True)),
                (
                    "plasmid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="plasmids.plasmid",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlasmidCollection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plasmid_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plasmid_collections",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plasmid Collection",
                "verbose_name_plural": "Plasmid Collections",
                "ordering": ("id", "name"),
            },
        ),
        migrations.AddField(
            model_name="plasmid",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plasmids",
                to="plasmids.plasmidcollection",
            ),
        ),
    ]
