# Generated by Django 5.2.8 on 2026-01-06 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plasmids", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plasmid",
            name="collection",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plasmids",
                to="plasmids.plasmidcollection",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plasmid",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="plasmid",
            name="length",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="PlasmidAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_type", models.CharField(max_length=50)),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("strand", models.IntegerField()),
                ("label", models.CharField(blank=True, max_length=200)),
                ("qualifiers", models.JSONField(blank=True, null=True)),
                (
                    "plasmid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="plasmids.plasmid",
                    ),
                ),
            ],
        ),
    ]
