# Generated by Django 5.0.14 on 2026-02-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plasmids", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plasmid",
            name="file_path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
