# Generated by Django 5.2.8 on 2026-01-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plasmids", "0003_alter_plasmidcollection_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="plasmid",
            name="genbank_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
