# Generated by Django 5.2.8 on 2026-01-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plasmids", "0004_plasmid_genbank_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plasmid",
            name="plasmidCollection",
        ),
    ]
