# Generated by Django 5.0.14 on 2026-01-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plasmids", "0005_remove_plasmid_plasmidcollection"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plasmid",
            old_name="plasmid_type",
            new_name="type",
        ),
    ]
