# Generated by Django 5.0.14 on 2026-02-05 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plasmids", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignTemplate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du Template"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Le fichier modèle .xlsx ou .csv",
                        upload_to="campaign_templates/",
                        verbose_name="Fichier Excel",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom de la Campagne"),
                ),
                (
                    "input_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="campaign_inputs/%Y/%m/",
                        verbose_name="Fichier d'entrée utilisé",
                    ),
                ),
                (
                    "run_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="ID d'exécution (Dossier)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Paramètres de simulation",
                    ),
                ),
                (
                    "results_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Données de résultats"
                    ),
                ),
                (
                    "output_files",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Liste des fichiers générés",
                    ),
                ),
                (
                    "collections_used",
                    models.ManyToManyField(
                        blank=True,
                        related_name="campaigns",
                        to="plasmids.plasmidcollection",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "produced_plasmids",
                    models.ManyToManyField(
                        blank=True, related_name="campaigns", to="plasmids.plasmid"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="simulations.campaigntemplate",
                        verbose_name="Template utilisé (Optionnel)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CampaignResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="simulations.campaign",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Result",
                "verbose_name_plural": "Campaign Results",
                "ordering": ("id", "created_at"),
            },
        ),
    ]
