# Generated by Django 5.2.8 on 2026-01-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plasmids", "0004_plasmid_genbank_data"),
        ("simulations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="collections_used",
            field=models.ManyToManyField(
                blank=True, related_name="campaigns", to="plasmids.plasmidcollection"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="output_files",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="campaign",
            name="parameters",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="campaign",
            name="results_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
