# Generated by Django 5.2.10 on 2026-02-02 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0002_campaign_collections_used_campaign_output_files_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du Template')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(help_text='Le fichier modèle .xlsx ou .csv', upload_to='campaign_templates/', verbose_name='Fichier Excel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ('-created_at',), 'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='campaign_inputs/%Y/%m/', verbose_name="Fichier d'entrée utilisé"),
        ),
        migrations.AddField(
            model_name='campaign',
            name='run_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="ID d'exécution (Dossier)"),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom de la Campagne'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='output_files',
            field=models.JSONField(blank=True, default=dict, verbose_name='Liste des fichiers générés'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, verbose_name='Paramètres de simulation'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='results_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Données de résultats'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='simulations.campaigntemplate', verbose_name='Template utilisé (Optionnel)'),
        ),
    ]
