# Generated by Django 5.2.8 on 2026-01-13 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("OWNER", "Owner"), ("MEMBER", "Member")],
                        default="MEMBER",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        # migrations.AlterField(
        #     model_name="team",
        #     name="members",
        #     field=models.ManyToManyField(
        #         blank=True,
        #         related_name="teams",
        #         through="teams.TeamMembership",
        #         to=settings.AUTH_USER_MODEL,
        #     ),
        # ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(
                fields=["team", "role"], name="teams_teamm_team_id_4d95f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(fields=["user"], name="teams_teamm_user_id_957e00_idx"),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                fields=("team", "user"), name="uniq_team_user"
            ),
        ),
    ]
