# Generated by Django 5.2.8 on 2026-01-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_alter_team_options_alter_team_name_teammembership_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
    ]
