# Generated by Django 5.2.8 on 2026-01-13 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_remove_team_members"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="teams",
                through="teams.TeamMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
