# Generated by Django 5.0.14 on 2026-01-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_team_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
