# Generated by Django 5.2.8 on 2026-01-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_alter_team_members_delete_teammembership"),
        ("teams", "0005_alter_team_name"),
    ]

    operations = []
